import React, { useState, useEffect, useCallback, useRef } from 'react';

interface TourStep {
  element: string | null;
  title: string;
  desc: string;
  action: (() => void) | null;
}

interface OnboardingTourProps {
  userRole: string;
  setActiveTab: (tab: string) => void;
  tourTrigger: number;
}

export const OnboardingTour: React.FC<OnboardingTourProps> = ({ userRole, setActiveTab, tourTrigger }) => {
  const [currentStep, setCurrentStep] = useState(0);
  const [run, setRun] = useState(false);
  const [targetRect, setTargetRect] = useState<DOMRect | null>(null);
  
  // Track if we've already scrolled for the current step to prevent glitching
  const scrolledForStep = useRef(-1);

  useEffect(() => {
    if (tourTrigger > 0) {
      setCurrentStep(0);
      scrolledForStep.current = -1;
      setTargetRect(null);
      setTimeout(() => setRun(true), 600);
    }
  }, [tourTrigger]);

  const buildSteps = useCallback((): TourStep[] => {
    const roleIntros: Record<string, string> = {
      'FLEET_SUPERVISOR': 'As a Fleet Supervisor, your goal is to maximize overall fleet readiness, monitor high-risk assets, and authorize critical maintenance decisions.',
      'MAINT_PLANNER': 'As a Maintenance Planner, you orchestrate repair schedules by reviewing AI recommendations and ensuring spare parts and facility slots are ready.',
      'MAINT_ENGINEER': 'As a Maintenance Engineer, you execute and validate AI-driven repair instructions, providing operational rationale for every action.',
      'SPARES_PLANNER': 'As a Spares Planner, you monitor critical inventory levels, track procurement lead times, and prevent parts shortages from delaying repairs.',
      'SYS_ADMIN': 'As a System Administrator, you monitor the cryptographic integrity of the audit chain, security events, and air-gapped system posture.',
    };

    const common: TourStep = {
      element: null,
      title: 'Welcome to AERIS',
      desc: roleIntros[userRole] || 'Welcome to the Aircraft Engine Reliability Intelligence System.',
      action: () => setActiveTab(userRole === 'SYS_ADMIN' ? 'security' : userRole === 'SPARES_PLANNER' ? 'spares' : userRole === 'MAINT_PLANNER' ? 'recommendations' : 'fleet'),
    };

    if (userRole === 'FLEET_SUPERVISOR') {
      return [
        common,
        { element: null, title: 'Fleet Overview Window', desc: 'This window gives you a bird\'s-eye view of your entire aircraft fleet. It highlights overall readiness and assets that need immediate attention.', action: () => setActiveTab('fleet') },
        { element: '.tour-kpi-row', title: 'Fleet KPI Dashboard', desc: 'Quickly check your Total Aircraft, Fleet Availability, and High Risk Assets (failure probability ≥ 70%).', action: null },
        { element: '.tour-fleet-filters', title: 'Search & Filters', desc: 'Filter your fleet by platform type (e.g., Su-30MKI) or risk level. You can also export this view to CSV.', action: null },
        { element: '.tour-fleet-table', title: 'Asset Register', desc: 'Displays each aircraft\'s status, AI-predicted failure risk, and estimated remaining useful life (RUL).', action: null },
        { element: null, title: 'Maintenance Queue Window', desc: 'This window is where AI-driven predictive maintenance recommendations are queued for your authorization.', action: () => setActiveTab('recommendations') },
        { element: '.tour-rec-list', title: 'Prioritized Queue', desc: 'Recommendations are automatically sorted by priority. CRITICAL items (red) require immediate action.', action: null },
        { element: '.tour-rec-detail', title: 'AI Analysis', desc: 'View the detailed failure probability (Risk Score) and RUL confidence intervals (P10/P50/P90) generated by the ML model.', action: null },
        { element: '.tour-record-decision', title: 'Authorize Decisions', desc: 'Enter your operational rationale here and click Accept, Defer, or Reject. Your decision overrides or confirms the AI.', action: null },
        { element: '.tour-evidence', title: 'Evidence Passport', desc: 'Every decision creates a cryptographically secure SHA-256 hash, ensuring a tamper-proof audit trail for defense compliance.', action: null },
      ];
    }

    if (userRole === 'MAINT_PLANNER') {
      return [
        common,
        { element: null, title: 'Maintenance Queue Window', desc: 'This is your main workspace for reviewing AI risk assessments and planning upcoming maintenance tasks.', action: () => setActiveTab('recommendations') },
        { element: '.tour-rec-list', title: 'Recommendation Queue', desc: 'Sorted by urgency. Look for items with a SHORTAGE in part status, as these will delay repairs.', action: null },
        { element: '.tour-rec-detail', title: 'Detailed Analysis', desc: 'Review the AI\'s confidence (Trust Score) and the exact component that requires replacement or inspection.', action: null },
        { element: '.tour-record-decision', title: 'Record Decision', desc: 'Authorize the work by typing a rationale and selecting an action. This is required before work orders are generated.', action: null },
        { element: null, title: 'Spares & Facilities Window', desc: 'Before finalizing a plan, use this window to check if you have the required parts and hangar space.', action: () => setActiveTab('spares') },
        { element: '.tour-spares-table', title: 'Inventory Readiness', desc: 'Tracks current stock vs minimum thresholds. Items marked SHORTAGE (red) have lead times exceeding the aircraft\'s RUL.', action: null },
        { element: '.tour-facility-cards', title: 'Facility Capacity', desc: 'Check available hangar slots and average turnaround times to optimally route aircraft for repair.', action: null },
      ];
    }

    if (userRole === 'MAINT_ENGINEER') {
      return [
        common,
        { element: null, title: 'Maintenance Queue Window', desc: 'Here you will find all the AI-generated work orders and recommendations assigned to your engineering team.', action: () => setActiveTab('recommendations') },
        { element: '.tour-rec-list', title: 'Assigned Tasks', desc: 'Your prioritized list of tasks. CRITICAL items represent high-risk anomalies detected by engine sensors.', action: null },
        { element: '.tour-rec-detail', title: 'AI Diagnostics', desc: 'Read the specific reason codes (e.g., ANOMALY_DETECTED) and RUL estimates to understand why the AI flagged this component.', action: null },
        { element: '.tour-record-decision', title: 'Execution Log', desc: 'Provide your engineering rationale here after inspection, and record whether the AI\'s recommendation was accepted or deferred.', action: null },
        { element: '.tour-evidence', title: 'Tamper-Proof Audit', desc: 'Your engineering sign-off is permanently hashed and stored securely in the evidence passport.', action: null },
      ];
    }

    if (userRole === 'SPARES_PLANNER') {
      return [
        common,
        { element: null, title: 'Spares & Facilities Window', desc: 'Your control center for inventory management and supply chain logistics.', action: () => setActiveTab('spares') },
        { element: '.tour-spares-table', title: 'Inventory Tracker', desc: 'Monitor part criticality and stock levels. Focus on parts where the procurement Lead Time is high.', action: null },
        { element: '.tour-facility-cards', title: 'Hangar Utilization', desc: 'Ensure that facilities have the required capabilities and open slots before parts are dispatched.', action: null },
        { element: null, title: 'Maintenance Queue Window', desc: 'Check this window to anticipate future spare part demand based on AI predictions.', action: () => setActiveTab('recommendations') },
        { element: '.tour-rec-list', title: 'Demand Forecasting', desc: 'These upcoming recommendations dictate which parts you need to order today to avoid future AOG (Aircraft on Ground) situations.', action: null },
      ];
    }

    if (userRole === 'SYS_ADMIN') {
      return [
        common,
        { element: null, title: 'Audit & Security Window', desc: 'This dashboard provides real-time monitoring of the system\'s cryptographic integrity and air-gap network posture.', action: () => setActiveTab('security') },
        { element: '.tour-security-posture', title: 'Security Checks', desc: 'Live validation of TLS, Content Security Policies, RBAC, and AES-256 field-level encryption.', action: null },
        { element: '.tour-audit-chain', title: 'Hash Chain Verification', desc: 'Monitors the unbroken SHA-256 chain of maintenance decisions. Click Verify to manually run an integrity check.', action: null },
        { element: '.tour-data-ingestion', title: 'Secure Data Ingestion', desc: 'Upload raw sensor CSVs here. The system validates them against the strict Appendix A Data Contract before ingestion.', action: null },
        { element: '.tour-security-events', title: 'Event Log', desc: 'A chronological, immutable log of all authentication attempts and infrastructure security events.', action: null },
      ];
    }

    // Default
    return [
      common,
      { element: null, title: 'Fleet Overview Window', desc: 'A high-level view of your aircraft and their readiness.', action: () => setActiveTab('fleet') },
      { element: '.tour-kpi-row', title: 'Key Metrics', desc: 'Monitor availability and risk across the entire fleet.', action: null },
    ];
  }, [userRole, setActiveTab]);

  const steps = buildSteps();

  const updateRect = useCallback(() => {
    if (!run || currentStep >= steps.length) return;
    const step = steps[currentStep];
    
    if (step.element) {
      const el = document.querySelector(step.element);
      if (el) {
        const rect = el.getBoundingClientRect();
        setTargetRect(rect);
        
        // Only scroll ONCE per step to prevent glitching/jittering
        if (scrolledForStep.current !== currentStep) {
          el.scrollIntoView({ behavior: 'smooth', block: 'center' });
          scrolledForStep.current = currentStep;
        }

        (el as HTMLElement).style.position = 'relative';
        (el as HTMLElement).style.zIndex = '999999';
        (el as HTMLElement).style.pointerEvents = 'auto';
        return;
      }
    }
    setTargetRect(null);
  }, [run, currentStep, steps]);

  useEffect(() => {
    window.addEventListener('resize', updateRect);
    window.addEventListener('scroll', updateRect, { passive: true });
    return () => {
      window.removeEventListener('resize', updateRect);
      window.removeEventListener('scroll', updateRect);
    };
  }, [updateRect]);

  // Use a fast interval to track dynamic DOM changes (like tab switching)
  // but since scrollIntoView is gated by scrolledForStep, it won't glitch.
  useEffect(() => {
    if (!run) return;
    const interval = setInterval(updateRect, 100);
    return () => clearInterval(interval);
  }, [run, updateRect]);

  const cleanupPrev = useCallback(() => {
    const prevStep = steps[currentStep];
    if (prevStep && prevStep.element) {
      const el = document.querySelector(prevStep.element);
      if (el) {
        (el as HTMLElement).style.position = '';
        (el as HTMLElement).style.zIndex = '';
        (el as HTMLElement).style.pointerEvents = '';
      }
    }
  }, [currentStep, steps]);

  const handleNext = () => {
    cleanupPrev();
    if (currentStep === steps.length - 1) {
      setRun(false);
    } else {
      const nextIdx = currentStep + 1;
      const nextStep = steps[nextIdx];
      if (nextStep.action) {
        nextStep.action();
      }
      setCurrentStep(nextIdx);
    }
  };

  const handlePrev = () => {
    cleanupPrev();
    if (currentStep > 0) {
      const prevIdx = currentStep - 1;
      const prevStep = steps[prevIdx];
      if (prevStep.action) {
        prevStep.action();
      }
      setCurrentStep(prevIdx);
      scrolledForStep.current = -1; // Force re-scroll if going back
    }
  };

  const handleSkip = () => {
    cleanupPrev();
    setRun(false);
  };

  if (!run || currentStep >= steps.length) return null;

  const step = steps[currentStep];

  // Calculate strict responsive popover positioning
  const isMobile = window.innerWidth < 640;
  let popoverStyle: React.CSSProperties = {};

  if (isMobile) {
    // On mobile, always fix to bottom so it never overflows horizontally or covers elements unpredictably
    popoverStyle = {
      bottom: '16px', left: '16px', right: '16px', width: 'auto',
      transform: 'none',
    };
  } else {
    // Desktop positioning
    const popoverWidth = 380;
    
    if (targetRect) {
      // Place near element
      let top = targetRect.bottom + 16;
      let left = targetRect.left + (targetRect.width / 2);
      let transform = 'translate(-50%, 0)';

      // Keep strictly within viewport horizontally
      const halfW = popoverWidth / 2;
      if (left - halfW < 16) left = halfW + 16;
      if (left + halfW > window.innerWidth - 16) left = window.innerWidth - halfW - 16;

      // Keep strictly within viewport vertically
      // If it overflows the bottom of the screen, flip it above the element
      if (top + 250 > window.innerHeight) {
        top = targetRect.top - 16;
        transform = 'translate(-50%, -100%)';
        
        // If it STILL overflows the top of the screen (element is too big), just center it on screen
        if (top - 250 < 0) {
          top = window.innerHeight / 2;
          left = window.innerWidth / 2;
          transform = 'translate(-50%, -50%)';
        }
      }
      
      popoverStyle = { top: `${top}px`, left: `${left}px`, transform, width: `${popoverWidth}px` };
    } else {
      // Intro step (no element) -> center strictly
      popoverStyle = { top: '50%', left: '50%', transform: 'translate(-50%, -50%)', width: `${popoverWidth}px` };
    }
  }

  // Safe clipPath for the overlay
  const clipPath = targetRect 
    ? `polygon(0% 0%, 0% 100%, ${Math.max(0, targetRect.left - 8)}px 100%, ${Math.max(0, targetRect.left - 8)}px ${Math.max(0, targetRect.top - 8)}px, ${Math.min(window.innerWidth, targetRect.right + 8)}px ${Math.max(0, targetRect.top - 8)}px, ${Math.min(window.innerWidth, targetRect.right + 8)}px ${Math.min(window.innerHeight, targetRect.bottom + 8)}px, ${Math.max(0, targetRect.left - 8)}px ${Math.min(window.innerHeight, targetRect.bottom + 8)}px, ${Math.max(0, targetRect.left - 8)}px 100%, 100% 100%, 100% 0%)`
    : 'none';

  return (
    <>
      {/* Overlay with cutout */}
      <div
        style={{
          position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
          zIndex: 999998,
          pointerEvents: targetRect ? 'none' : 'auto',
          background: targetRect ? 'transparent' : 'rgba(0,0,0,0.7)',
          boxShadow: targetRect ? '0 0 0 9999px rgba(0,0,0,0.7)' : 'none',
          clipPath,
          transition: 'all 0.3s ease',
        }}
      />

      {/* Popover Card */}
      <div
        className="fixed p-5 rounded-xl shadow-2xl flex flex-col gap-3"
        style={{
          backgroundColor: 'var(--color-bg-panel)',
          border: '1px solid var(--color-border)',
          zIndex: 999999,
          maxHeight: isMobile ? '60vh' : '85vh',
          overflowY: 'auto',
          transition: 'top 0.3s ease, left 0.3s ease, bottom 0.3s ease, transform 0.3s ease',
          ...popoverStyle,
        }}
      >
        {/* Header */}
        <div className="flex items-start justify-between gap-3">
          <div className="flex-1 min-w-0">
            <h3 className="text-base font-bold leading-tight" style={{ color: 'var(--color-text-primary)' }}>
              {step.title}
            </h3>
          </div>
          <span
            className="text-[11px] font-bold px-2 py-0.5 rounded-full shrink-0"
            style={{ backgroundColor: 'var(--color-primary-strong)', color: '#fff' }}
          >
            {currentStep + 1}/{steps.length}
          </span>
        </div>

        {/* Progress bar */}
        <div className="w-full h-1 rounded-full overflow-hidden" style={{ backgroundColor: 'var(--color-bg-inset)' }}>
          <div
            className="h-full rounded-full transition-all duration-500 ease-out"
            style={{
              width: `${((currentStep + 1) / steps.length) * 100}%`,
              backgroundColor: 'var(--color-primary-strong)',
            }}
          />
        </div>

        {/* Description */}
        <p className="text-[13px] leading-relaxed" style={{ color: 'var(--color-text-secondary)' }}>
          {step.desc}
        </p>

        {/* Buttons */}
        <div className="flex items-center justify-between gap-2 pt-2 mt-auto">
          <button
            onClick={handleSkip}
            className="text-[12px] font-medium hover:underline transition-colors"
            style={{ color: 'var(--color-text-muted)' }}
          >
            Skip Tour
          </button>

          <div className="flex items-center gap-2">
            {currentStep > 0 && (
              <button
                onClick={handlePrev}
                className="px-3 py-1.5 text-[12px] font-medium rounded-lg transition-colors"
                style={{
                  color: 'var(--color-text-secondary)',
                  backgroundColor: 'var(--color-bg-inset)',
                  border: '1px solid var(--color-border)',
                }}
              >
                Back
              </button>
            )}
            <button
              onClick={handleNext}
              className="px-4 py-1.5 text-[12px] font-semibold text-white rounded-lg transition-transform hover:scale-105 active:scale-95"
              style={{ backgroundColor: 'var(--color-primary-strong)' }}
            >
              {currentStep === steps.length - 1 ? 'Finish' : 'Next'}
            </button>
          </div>
        </div>
      </div>
    </>
  );
};
